source ~/.env
source ~/.alias

export EDITOR="nvim"
export ZSH="$HOME/.oh-my-zsh"
export ZSH_THEME="robbyrussell"
export SSH_AUTH_SOCK="$XDG_RUNTIME_DIR/ssh-agent.socket"

path+=/usr/bin
path+=/opt/cuda/bin
path+=$HOME/.local/bin
export PATH

plugins=(
    git
    zsh-autosuggestions
)

source $ZSH/oh-my-zsh.sh
. "$HOME/.cargo/env"

# fzf
export FZF_DEFAULT_COMMAND="fd . $HOME"
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
export FZF_ALT_C_COMMAND="fd -t d . $HOME"
source <(fzf --zsh)


# onnxruntime
export ORT_LIB_LOCATION="/opt/onnxruntime"

# todo: export useful docker command for finding host ip
alias dockerhost=ip addr show docker0 | grep -Po 'inet \K[\d.]+'

#export CLOUDSDK_PYTHON=/home/jayden/.pyenv/shims/python3
export CLOUDSDK_PYTHON=/usr/bin/python3

# kitty fix
[[ "$TERM" == "xterm-kitty" ]] && alias ssh="TERM=xterm-256color ssh"
