source ~/.env
source ~/.alias

export EDITOR="nvim"
alias n="cd $HOME/.config/nvim"

export ZSH="$HOME/.oh-my-zsh"
export ZSH_THEME="robbyrussell"


# path
path+=/usr/bin
path+=/opt/cuda/bin
export PATH


plugins=(
    git
    zsh-autosuggestions
)
source $ZSH/oh-my-zsh.sh
. "$HOME/.cargo/env"

# fzf
export FZF_DEFAULT_COMMAND="fd . $HOME"
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
export FZF_ALT_C_COMMAND="fd -t d . $HOME"
source <(fzf --zsh)


# onnxruntime
export ORT_LIB_LOCATION="/opt/onnxruntime"

# pnpm
export PNPM_HOME="/home/jaydenelliott/.local/share/pnpm"
case ":$PATH:" in
  *":$PNPM_HOME:"*) ;;
  *) export PATH="$PNPM_HOME:$PATH" ;;
esac
# pnpm end


# todo: export useful docker command for finding host ip
alias dockerhost=ip addr show docker0 | grep -Po 'inet \K[\d.]+'

export PYENV_ROOT="$HOME/.pyenv"
[[ -d $PYENV_ROOT/bin ]] && export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init - zsh)"
export CLOUDSDK_PYTHON=/home/jayden/.pyenv/shims/python3

# kitty fix
[[ "$TERM" == "xterm-kitty" ]] && alias ssh="TERM=xterm-256color ssh"
