[desktop]
depends = ["shell", "desktop"]

[docker]
depends = ["shell", "nvim"]

[shell.files]
pacdef = "~/.config/pacdef"
"term/.gitconfig" = "~/.gitconfig"
"term/.gitconfig-visualcortex" = "~/.gitconfig-visualcortex"
"term/zshrc" = "~/.zshrc"
"term/alias" = "~/.alias"
"term/nvim" = "~/.config/nvim"
"term/ssh" = "~/.ssh"
"term/lazydocker.yml" = "~/.config/lazydocker/config.yml"
"term/lazygit.yml" = "~/.config/lazygit/config.yml"
"term/dircolors" = "~/.dircolors"
"term/tealdeer.toml" = "~/.config/tealdeer/config.toml"
"term/docker.json" = { target = "/etc/docker/daemon.json", owner = 0, type = "symbolic" }

[desktop.files]
"term/kitty" = "~/.config/kitty"
"desktop/discord.json" = "~/.config/discord/settings.json"
"desktop/wallpapers" = "~/.config/desktop/wallpapers"
"desktop/ulauncher.json" = "~/.config/ulauncher/settings.json"
