[desktop]
depends = ["shell", "desktop"]

[docker]
depends = ["shell", "nvim"]

[shell.files]
pacdef = "~/.config/pacdef"
"term/zshrc" = "~/.zshrc"
"term/alias" = "~/.alias"
"term/nvim" = "~/.config/nvim"
"term/kitty" = "~/.config/kitty"
"term/ssh" = "~/.ssh"
"term/lazydocker.yml" = "~/.config/lazydocker/config.yml"
"term/lazygit.yml" = "~/.config/lazygit/config.yml"
"term/dircolors" = "~/.dircolors"

[desktop.files]
"desktop/wallpapers" = "~/.config/desktop/wallpapers"
"desktop/ulauncher.json" = "~/.config/ulauncher/settings.json"
