[desktop]
depends = ["shell", "gui"]

[docker]
depends = ["shell", "nvim"]

[shell.files]
zshrc = "~/.zshrc"
alias = "~/.alias"
pacdef = "~/.config/pacdef"
nvim = "~/.config/nvim"
kitty = "~/.config/kitty"
ssh = "~/.ssh"
"lazydocker.yml" = "~/.config/lazydocker/config.yml"
"lazygit.yml" = "~/.config/lazygit/config.yml"

[gui.files]
wallpapers = "~/.config/wallpapers"

[hyprland.files]
hypr = "~/.config/hypr"
