[desktop]
depends = ["shell", "gui"]

[docker]
depends = ["shell", "nvim"]

[shell.files]
pacdef = "~/.config/pacdef"
"term/zshrc" = "~/.zshrc"
"term/alias" = "~/.alias"
"term/nvim" = "~/.config/nvim"
"term/kitty" = "~/.config/kitty"
"term/ssh" = "~/.ssh"
"term/lazydocker.yml" = "~/.config/lazydocker.yml"
"term/lazygit.yml" = "~/.config/lazygit.yml"

[gui.files]
"desktop/wallpapers" = "~/.config/desktop/wallpapers"
