[desktop]
depends = ["shell", "gui"]

[docker]
depends = ["shell", "nvim"]

[shell.files]
zshrc = "~/.zshrc"
alias = "~/.alias"
nvim = "~/.config/nvim"
kitty = "~/.config/kitty"
"lazydocker.yml" = "~/.config/lazydocker/config.yml"
"lazygit.yml" = "~/.config/lazygit/config.yml"

[gui.files]
wallpapers = "~/.config/wallpapers"
fonts = "~/.local/share/fonts"

[hyprland.files]
hypr = "~/.config/hypr"
